<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>1.0.2</Version>
    <PackageReleaseNotes>
      [2026-07-21] v1.0.1 Dependency update from Senparc.CO2NET.Cache.Dapr to 1.1.2
      [2026-07-22] v1.0.2 Dependency update from Senparc.CO2NET.Cache.Dapr to 1.1.3
    </PackageReleaseNotes>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="1.9.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Senparc.CO2NET.Cache.Dapr\Senparc.CO2NET.Cache.Dapr.csproj" />
  </ItemGroup>

</Project>
