//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senparc.Common.SDK {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Senparc.Common.SDK.Base.System.Message_CN", typeof(Message_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 查询结果为空 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件信息不存在 的本地化字符串。
        /// </summary>
        internal static string FileInfoNoExist {
            get {
                return ResourceManager.GetString("FileInfoNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的请求地址 的本地化字符串。
        /// </summary>
        internal static string NoAddress {
            get {
                return ResourceManager.GetString("NoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您还没有登录，请您登录 的本地化字符串。
        /// </summary>
        internal static string NoLogin {
            get {
                return ResourceManager.GetString("NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改的新密码不能与原来的密码一直 的本地化字符串。
        /// </summary>
        internal static string OldPwdSameAsNewPwd {
            get {
                return ResourceManager.GetString("OldPwdSameAsNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数验证未通过 的本地化字符串。
        /// </summary>
        internal static string ParaNoPass {
            get {
                return ResourceManager.GetString("ParaNoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册验证码不存在 的本地化字符串。
        /// </summary>
        internal static string RegisterVerificationCodeNoExist {
            get {
                return ResourceManager.GetString("RegisterVerificationCodeNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器错误 的本地化字符串。
        /// </summary>
        internal static string ServerData {
            get {
                return ResourceManager.GetString("ServerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误信息 的本地化字符串。
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件写入失败 的本地化字符串。
        /// </summary>
        internal static string UploadFileWriteFailed {
            get {
                return ResourceManager.GetString("UploadFileWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户被禁用 的本地化字符串。
        /// </summary>
        internal static string UserBeBanned {
            get {
                return ResourceManager.GetString("UserBeBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已经被禁用 的本地化字符串。
        /// </summary>
        internal static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已经存在 的本地化字符串。
        /// </summary>
        internal static string UserIsExist {
            get {
                return ResourceManager.GetString("UserIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string UserNoExist {
            get {
                return ResourceManager.GetString("UserNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户未登录 的本地化字符串。
        /// </summary>
        internal static string UserNoLogin {
            get {
                return ResourceManager.GetString("UserNoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        internal static string UserPwdNoError {
            get {
                return ResourceManager.GetString("UserPwdNoError", resourceCulture);
            }
        }
    }
}
