<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Version>1.0.2</Version>
		<PackageReleaseNotes>
			[2026-07-21] v1.0.1 更新 JSON 序列化兼容测试
			1、将 Redis 性能测试中的 Newtonsoft.Json 调用迁移到 System.Text.Json。
			[2026-07-22] v1.0.2 Dependency update from Senparc.CO2NET.Cache.Redis to 5.2.3
		</PackageReleaseNotes>

		<IsPackable>false</IsPackable>

		<Configurations>Debug;Release;Test</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" Version="2.5.187" />
		<PackageReference Include="MessagePackAnalyzer" Version="1.6.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
		<PackageReference Include="Moq" Version="4.9.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="1.4.0" />
		<PackageReference Include="MSTest.TestFramework" Version="1.4.0" />
		<PackageReference Include="Microsoft.Net.Http.Headers">
			<Version>2.2.8</Version>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.2" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.0" />
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' or '$(TargetFramework)' == 'netcoreapp3.1' or '$(TargetFramework)' == 'net6.0' ">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Senparc.CO2NET.Cache.Redis.RedLock\redlock-cs\src\Senparc.CO2NET.Cache.Redis.RedLock.csproj" />
		<ProjectReference Include="..\Senparc.CO2NET.Cache.Redis\Senparc.CO2NET.Cache.Redis.csproj" />
		<ProjectReference Include="..\Senparc.CO2NET.Tests\Senparc.CO2NET.Tests.csproj" />
	</ItemGroup>

</Project>
